### ISSUE TITLE
Oscar Signals

### ISSUE THREAD

**Issue by ehmadzubair** [django-oscar/django-oscar-api#155]
@maerteijn Just found out that no signals are being dispatched related to the product or the user. Is that by design?

**Comment by maerteijn** [comment]
I don't understand which signals you mean and when they should be dispatched?

**Comment by ehmadzubair** [comment]
@maerteijn So there's the following signal which should be dispatched whenever a product is viewed.

```
product_viewed = django.dispatch.Signal(
    providing_args=["product", "user", "request", "response"])
```

Should we be dispatching it in the `ProductDetail` view?

**Comment by maerteijn** [comment]
Ah, now I understand what you mean. 

The signal you mention is meant for a case when an end-user is looking at the product in a frontend of the webshop. This is not necessarily the case when using the REST API, so that is why it is not included  per default.

However, overriding the view and  triggering it for your project is really easy to do.

**Comment by ehmadzubair** [comment]
@maerteijn Yep. Just did it.

**Comment by maerteijn** [comment]
👍
