### ISSUE TITLE
WDYT about adding `pytest`?

### ISSUE THREAD

**Issue by samitnuk** [django-oscar/django-oscar-api#175]
With `pytest` we will be able to remove `self.assert*`s with builtin `assert`. I think this gives at least two pros:
- Improves tests readability (+ adds proper syntax highlighting everywhere);
- Outputs better/more understandable logs for failed tests.

I understand that this will add additional dependencies (`pytest`, `pytest-django`), but if you think that this can be useful, I will try to add needed changes when I will be able.

**Comment by specialunderwear** [comment]
Hi thank you for bringing this up. We are actually not using pytest on purpose and by design. There are various reasons for this.

First, we really do not want to add any unnescessary dependencies. To me pytest offers nothing more than a different way of stating things. Not only is that against the zen of python, but it is not useful at all to beginners that learn from the django docs.

To me pytest is completely unintelligable. In many cases, I can not find out what is wrong when a test fails by just following the code path. Knowledge is required of the way pytest injects values into arguments. That to me is too much magic and totally not worth giving up a perfectly fine, working, included in the standard lib, unittest and doctest module.

While I do think you’ve got a point that the tests are not super well organized. The reason is, that I do not particularly enjoy (hate) writing tests. So I do not give it my best effort, I allow myself this flaw of character because tests are never running in production. Please do note vast amount of real scneario’s tested in oscarapi! We do not test for coverage only!

So while I do agree that the tests can be much improved, I propose the solution would be to simplify and restructure the tests, like you have allready been doing, instead of rewriting all the tests in pytest, making them unaccessible to people that know python but never encountered pytest before.

If you think there are more advantages  to pytest beyond removing “self.” in an assertion I’d love to hear about them.

**Comment by maerteijn** [comment]
Just some extra notes:
- pytest can also run the existing tests as is, no need to rewrite them to pytest specific syntax
- pytest nowadays gives some clear and readable output, so it would improve readability of failed tests, but this is personal preference

So it is already possible to use the pytest runner for personal preferences without touching the current tests

**Comment by samitnuk** [comment]
@specialunderwear @maerteijn 
Thank you for your answers. They are very interesting and cognitive. Totally agree that "this is personal preference" since `pytest` is just one of many tools. 

I think I am more familiar with `pytest` because mostly all projects I worked with are using it (e.g. Oscar). I used it to run the current tests as well 😉

Should we close this issue now?
