### ISSUE TITLE
Need help regarding few things I find missing

### ISSUE THREAD

**Issue by noodlebreak** [django-oscar/django-oscar-api#211]
So I was considering using django-oscar to spin up quickly an ecommerce store with basic stuff - products, categories, reviews, ratings, users login, addresses, order, etc

But I also needed just the REST API from the backend, not everything that django-oscar gives out of the box. Naturally, after searching, I landed here.

So I was going through the docs and playing around, and first of all, kudos to you founder and contributors of this awesome project! So much work already done! So much value I can get after the initial setup, which normally would take at least 2 weeks of work (if not having django oscar as well).

That being said, there are a few requirements in my project that I couldn't find in this project:

- product and category search API
- address API
- configuring returning full JSON of product snapshot in order
- user detail gives permission error (bug ?)
- user account APIs - change password, edit profile

Can someone point me in the right direction as to how to get started in adding these things for customisation? The customization docs has a very basic example, and I want to see some examples on how to:

- include full json instead of API link for a resource (eg., product URL in basket instead of detail json)
- add new routes

**Comment by maerteijn** [comment]
Hi @noodlebreak 

The customization documentation is written for an override method that is specific for OscarAPI. Note that it is possible to override almost every aspect of OscarAPI with it, just plug in your own serializers and views where needed (_configuring returning full JSON of product snapshot_ could be  easily be done with this).

Note that OscarAPI is a Django Rest Framework application, so see the [Documentation of Django Restframework](https://www.django-rest-framework.org/) how the framework works so you know where to start. Reading the source code of OscarAPI will help as well. 

The [override example](https://github.com/django-oscar/django-oscar-api/tree/master/override-example) shows how you would override the product serializer for example (this way you could build _include full json instead of API link for a resource_).
