### ISSUE TITLE
Oscar-api Order Placement issue

### ISSUE THREAD

**Issue by theArsalanM** [django-oscar/django-oscar-api#254]
From Django-oscar's code, an Order is placed by calling `handle_order_placement(...)` from `apps/checkout`.
```
    def handle_order_placement(self, order_number, user, basket,
                               shipping_address, shipping_method,
                               shipping_charge, billing_address, order_total,
                               **kwargs):
        order = self.place_order(
            order_number=order_number, user=user, basket=basket,
            shipping_address=shipping_address, shipping_method=shipping_method,
            shipping_charge=shipping_charge, order_total=order_total,
            billing_address=billing_address, **kwargs)
        basket.submit()
        return self.handle_successful_order(order)
```

This works perfectly fine for oscar, but in **django-oscar-api's** implementation of Order placement, I wonder why `place_order(...)` is called directly instead of sticking to oscar's default approach? Maybe we need to create oscar-api's own OrderPlacementMixin to rewrite Restful structure for `handle_successful_order()`.

Oscar API places order by calling `place_order()` directly from `serializers/checkout`.
The problem? It ends up with 2 issues:
- Order Confirmation email is not being sent when Order placed via API
- Basket status remains `Frozen` even after order placement. It should have been changed to `Submitted`

I wanted to understand is it intentionally left behind for developers to implement on their own, or can we add it to core code?

**Comment by maerteijn** [comment]
One of the reasons that we can't use Oscar's [`handler_order_placement`](https://github.com/django-oscar/django-oscar/blob/f333a827734761d8f1b21db94f5ae9654be31169/src/oscar/apps/checkout/mixins.py#L93) is that the [`handle_successful_order`](https://github.com/django-oscar/django-oscar/blob/f333a827734761d8f1b21db94f5ae9654be31169/src/oscar/apps/checkout/mixins.py#L238) method is not really generic:

```python
        # Flush all session data
        self.checkout_session.flush()

        # Save order id in session so thank-you page can load it
        self.request.session['checkout_order_id'] = order.id

        response = HttpResponseRedirect(self.get_success_url())
```

In the API we don't use a session, nor is the `HttpResponseRedirect` a desired response.

In the flow of OscarAP, there is a possibility that payment fails or that a user cancels one of the payment methods. Then you would want to resubmit your basket again with another payment. That's why we don't [set the status to submitted at this point](https://github.com/django-oscar/django-oscar-api/blob/37308937c4310f9f24c37347ef801f950e2bec3e/oscarapi/tests/unit/testcheckout.py#L137) and do not send a confirmation email yet.

This is also explained in a note in the documentation: https://django-oscar-api.readthedocs.io/en/latest/topics/communicate_with_the_api.html#place-an-order-checkout

It's up to the developer what to do from here. It can be as easy a registeing a `receiver` for the `oscarapi_post_checkout` signal and you call the methods you would like to call:

```python
@receiver(oscarapi_post_checkout)
def post_checkout(sender, **kwargs):
    # send email, do some checks, submit basket etc.
```

See also the [oscar-api-checkout](https://gitlab.com/thelabnyc/django-oscar/django-oscar-api-checkout/-/blob/master/src/oscarapicheckout/handlers.py#L14) plugin which continues where oscarpi stops, including a nice wrapper for sending the confirmation email.
