### ISSUE TITLE
Ajax PUT request to update line quantity

### ISSUE THREAD

**Issue by dentemm** [django-oscar/django-oscar-api#78]
When trying to update the quantity of a line in my basket I am getting this AssertionError: 

> AssertionError: The `.update()` method does not support writable nested fields by default.
> Write an explicit `.update()` method for serializer `oscarapi.serializers.basket.BasketLineSerializer`, or set `read_only=True` on nested serialiser fields.

Am I doing anything wrong here? I am basically executing the exact same code as explained in the Example Usage section of the docs.

Thank you!

**Comment by maerteijn** [comment]
Which version of oscarapi do you use? I will take a look tommorow then

**Comment by dentemm** [comment]
Thanks for your quick response! 

django-oscar-api==1.0.7

**Comment by maerteijn** [comment]
@dentemm Ok found it. This is because of the `AttributeSerializer` defined in the `BasketLineSerializer`:

https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/serializers/basket.py#L96

It should not be possible to update these directly without an update view so `django-rest-framework` complaining is justified. In our tests this was not tested correctly so we are going to address this in the near future. For now I released version 1.0.8 to fix this problem by setting the attribute to read-only, see https://pypi.python.org/pypi/django-oscar-api/1.0.8

**Comment by dentemm** [comment]
Thanks a lot Maerteijn, it works!

**Comment by maerteijn** [comment]
Ok, I will leave this issue open until we have a real proper fix. Thanks for reporting!
