### ISSUE TITLE
Oscar Api Checkout

### ISSUE THREAD

**Issue by vsanchez2187** [django-oscar/django-oscar-api#93]
Hello , in terms of checkout process during the request, the current latest version of django-oscar api has a checkout method already implemented.But , i need to know how to use PayPal with django oscar api and Stripes as a payment gateway.I mean , when someone try to buy you most select a payment type as the demo site has show.

Can someone explain how can i do that ? from the Api side???

**Comment by maerteijn** [comment]
Hi @vsanchez2187,

Normally when you do a checkout in an E-Commerce website you choose your payment provider, do some stuff you need to do in advance (register your payment, add success and error callbacks etc) and then redirect to the payment page of the specific provider.

In Oscar API this is no different. However, you need to implement this yourself because of the major difference in payment provider API's. The API is expecting you that you will register a view with the name `api-payment` so it will return the correct url with all callback functions etc. What should be done with this or how you implement this is up to you. 

See also the notes here: http://django-oscar-api.readthedocs.io/en/latest/usage/communicate_with_the_api.html#place-an-order-checkout  (the note about `payment_url`).

**Comment by vsanchez2187** [comment]
Thanks @maerteijn , so for example if i want to use PayPal , i should download django-oscar-paypal . and implement a redirect view my self and call the redirect url after the order has been made.? Is that correct ?

I was reading about checkouts process , and there is a library that mades payments for django-oscar api called https://pypi.python.org/pypi/django-oscar-api-checkout , it has more understanding method for payment and  you can add your own payment providers wich is very cool.So , have you read a about it ?

My questions is for your experience , wich is the best way for doing that.

Thanks

**Comment by maerteijn** [comment]
Hi @vsanchez2187 I'm not sure what django-oscar-paypal is doing but I suspect that it has all the stuff you need. So what you say is correct.

No, I did not know Craig developed this, looks pretty promising. I will check it out!

**Comment by specialunderwear** [comment]
Hi oscarapi offers you a way to integrate payments, but does not offer any payment fuctionality by itself, because it is to specific to the payment providers.

What oscarapi want you to do is as follows:

implement a view and register it's url:
```
urls = urlpatterns('',
   url(r"^paymentsetup/(?P<pk>[0-9]+)/$", TheViewThatSetsUpPayment.as_view(), name='api-payment'),
  # the rest of your views
)
```

If you do this, every order object that is created with the checkout api, get's a payment url,that you can use to move onto payment. So that means payment comes AFTER checkout. Same way as in a physical shop, the cassiere will scan all the items you want to buy, and then tells you what you need to pay. Now you can pay with credit card or PIN or cash. This is no different.

What you should implement in that view (TheViewThatSetsUpPayment) is setting up the payment with the payment provider. The view get's the order is as a parameter, so you can query for it and read any details you need for the payment provider. The you should make some requests to the payment provider to set up the payment. Usually they will then provide you with a url that you should redirect your client to. So that is also what you should do in your ``TheViewThatSetsUpPayment`` after setting up the payment with the payment provider, at the end of the view return a redirect to the payment provider's url.

If you don't redirect to an external site, but have all the payment pages in your own site, just redirect to an internal page.

That is all the support we offer, all the stuff you need to do to confirm payment, create payment events with payment sources, change the order status, should be in your own code, because we feel it is very specific to whichever provider you are using.

So the library you linked above does implement features that handle Payment events and order status for you. @crgwbr maybe you can fill in some blanks on how this is supposed to fit in the story I just told.

**Comment by jmarshall9120** [comment]
So I'm in the middle of this right now and some links on this ticket are broken.  Can someone look at this example and let me know if this is the 'recomended' way to implement.   I feel a simple example added to this issue is better than creating a whole new issue, but happy to do so if that is needed.

I already I have my frontend payment stuff done (stripe in my case) during basket and confirmation.  I need to now confirm payment sever-side and generate an order.  So is use the `/api/checkout` [endpoint](https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/views/checkout.py).

Unlike django-oscar this view doesn't seem to have a hook for payment gateway stuff so I override the checkout view putting my own checkout.py in:
```
mySite/myApp/api/views/checkout.py
```

Then I override post like this:
```
from oscarapi.views import checkout
from oscarapi.basket import operations
from rest_framework.response import Response
class CheckoutBasket(checkout.CheckoutView):
    
    def post(self, request, *args, **kwargs):

        basket = operations.get_basket(self.request)
        try:
            myCustomStripeProcess(self.request)
        except: MyCustomStripeException as e
            return Response(e.message, status.HTTP_406_NOT_ACCEPTABLE)
        return super().post(request, *args, **kwargs)
```

The above solution works fine, but is it the intended solution for payment processing?  Not sure.
